name: Build and Deploy

on:
  push: 
  workflow_dispatch:
    inputs:      
      build:
        description: 'Run Job build'
        required: false
        default: true
      deploy:
        description: 'Run Job deploy'
        required: false
        default: true
      delete:
        description: 'Run Job delete'
        required: false
        default: false
env:
  PROJECT_ID: linear-stock-388107
  GCR_HOSTNAME: us.gcr.io
  GCR_REGISTRY: app-engine-tmp
  GKE_CLUSTER: gke-cluster
  GKE_ZONE: us-central1-a
  IMAGE_NAME: app
  IMAGE_TAG: ${{ github.sha }}
  INGRESS_DELETE: FALSE


jobs:
  build:
    name: Build Docker Image
    runs-on: self-hosted
    # if: ${{ github.event.inputs.build == 'true' }}
    

